import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavbarLayout/Navbar";
import HistoryBar from "@/components/NavbarLayout/HistoryBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FourGPT",
  description: "Generated by create next app",
};

const MockHistoryItem = [
  {
    title: "How to cook mac&cheese",
    url: "",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex fixed w-full flex-col h-screen">
          <Navbar />
          <div className="flex h-full pt-12">
            <HistoryBar MockHistoryItem={MockHistoryItem} />
            <div className="h-full w-full bg-gray-900">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
