import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavbarLayout/Navbar";
import HistoryBar from "@/components/NavbarLayout/HistoryBar";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FourGPT",
  description: "Generated by create next app",
};

const MockHistoryItem = [
  {
    title: "How to cook mac&cheese",
    url: "",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className={inter.className}>
        <SpeedInsights />
        <div className="flex fixed w-full flex-col h-screen">
          <Navbar />
          <div className="flex h-full pt-12">
            <HistoryBar MockHistoryItem={MockHistoryItem} />
            <div className="h-full w-full bg-gray-800">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
